name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - jupyterlab=4.0.9
  - jupyter=1.0.0
  #- pandas-profiling==2.11.0
  - pandas-profiling=3.1.0
  # - ydata_profiling=4.6.3
  - pyarrow=2.0
  - seaborn=0.12.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - numpy==1.23.5
