name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1 
  - jupyterlab=3.0.10
  #- jupyter=1.0.0
  - ipython=7.21.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  #- pandas-profiling=2.11.0
  - pandas-profiling=3.6.1
  - pydantic=1.8.2
  - pyarrow=2.0
  - pip:
      - wandb==0.10.31
      - numpy==1.23.5
