name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  #- python=3.10.0
  - wandb=0.13.10
  - pandas=1.1.4   #2.1.3
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3     #23.3.1
  - pip:
      #- mlflow==2.8.1
      #- wandb==0.16.0