name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.2.1 #1.14.1 #2.1.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3 #22.3.1 
  - wandb=0.13.10
  - pip:
  #    - wandb==0.10.31
       - numpy==1.23.5
