name: nyc_38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - mlflow=1.14.1   #2.1.1  #1.14.1
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.10   #3.5.3  #3.0.10
  - cookiecutter=1.7.2
  - hydra-core=1.0.6  #1.3.1  #1.0.6
  - matplotlib=3.3.4
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3  #22.3.1  #20.3.3
  #- wandb=0.13.10
  - pip:
      - wandb==0.10.31
      - numpy==1.23.5