name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  #- wandb=0.13.10
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1 #1.14.1
  #- mlflow=2.2.1 #1.14.1
  #- scikit-learn=1.3.2
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - wandb==0.10.21
      # note: numpy newer version to get rid of
      # AttributeError (deprecation on 1.20)
      - numpy==1.23.5
